### ISSUE TITLE
pytest.mark.asyncio

### ISSUE THREAD

**Issue by Olegt0rr** [OCCCAS/aiogram_tests#13]
Since all related test should be async, it would be nice add global async support

pyproject.toml example:
```toml
[tool.pytest.ini_options]
asyncio_mode = "auto"
```
